# ml/train_future_skills_model.py

"""ML model training script for Module 3 - Future Skills.

This script:
- Loads the dataset CSV generated by:
    python manage.py export_future_skills_dataset
- Builds a scikit-learn pipeline:
    - OneHotEncoder for job_role_name and skill_name
    - StandardScaler for numeric features
    - RandomForestClassifier as the classification model
- Saves the complete pipeline (preprocessing + model) to:
    artifacts/models/future_skills_model_vX.pkl (with versioning)
- Generates a JSON metadata file for MLOps traceability

This script is intentionally Django-independent (no settings required).
"""

import argparse
import json
import logging
from datetime import datetime
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from typing import Dict, List, Optional, Tuple
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import SimpleImputer
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    brier_score_loss,
    classification_report,
    cohen_kappa_score,
    confusion_matrix,
    precision_recall_fscore_support,
)
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
ARTIFACTS_DIR = PROJECT_ROOT / "artifacts"
DEFAULT_DATASET_DIR = ARTIFACTS_DIR / "datasets"
DEFAULT_MODEL_DIR = ARTIFACTS_DIR / "models"
JOBLIB_CACHE_DIR = ARTIFACTS_DIR / "cache" / "joblib"

for directory in (
    ARTIFACTS_DIR,
    DEFAULT_DATASET_DIR,
    DEFAULT_MODEL_DIR,
    JOBLIB_CACHE_DIR,
):
    directory.mkdir(parents=True, exist_ok=True)

# Configure logging
logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s")


ALLOWED_LEVELS = {"LOW", "MEDIUM", "HIGH"}
ALLOWED_PROVENANCE = {"BRONZE", "SILVER", "GOLD"}
DEFAULT_ALLOWED_PROVENANCE = ["SILVER", "GOLD"]
LABEL_PROVENANCE_COLUMN = "label_provenance"
AS_OF_DATE_COLUMN = "as_of_date"


def load_dataset(csv_path: Path) -> pd.DataFrame:
    """Load and validate the future skills dataset from CSV.

    Args:
        csv_path: Path to the CSV file containing the dataset

    Returns:
        Filtered pandas DataFrame with validated future skills data

    Raises:
        FileNotFoundError: If the CSV file doesn't exist
        ValueError: If required target column is missing
    """
    if not csv_path.exists():
        raise FileNotFoundError(f"Dataset CSV not found: {csv_path}")

    df = pd.read_csv(csv_path)

    # Accept either 'future_need_level' or 'level' as the target column
    target_col = None
    if "future_need_level" in df.columns:
        target_col = "future_need_level"
    elif "level" in df.columns:
        target_col = "level"
    else:
        raise ValueError("Target column 'future_need_level' or 'level' is missing from dataset.")

    # Filter for allowed levels (LOW / MEDIUM / HIGH)
    before = len(df)
    df = df[df[target_col].isin(ALLOWED_LEVELS)].copy()
    after = len(df)

    if after == 0:
        raise ValueError(f"No valid rows with future_need_level in {ALLOWED_LEVELS}.")

    if after < before:
        logger.warning(f"{before - after} row(s) filtered out where future_need_level " f"was not in {ALLOWED_LEVELS}.")

    # Attach target_col as attribute for downstream use
    df._target_col = target_col
    return df


def _apply_label_provenance_filter(
    df: pd.DataFrame,
    allowed_provenance: Optional[List[str]],
) -> Tuple[pd.DataFrame, Dict[str, int]]:
    """Filter dataset by allowed label provenance values (if requested)."""
    if not allowed_provenance:
        return df, {}

    if LABEL_PROVENANCE_COLUMN not in df.columns:
        print("[WARN] label_provenance column missing; skipping provenance filter.")
        return df, {}

    allowed_set = {value.upper() for value in allowed_provenance}
    invalid = sorted([value for value in allowed_set if value not in ALLOWED_PROVENANCE])
    if invalid:
        raise ValueError(f"Invalid label provenance values: {invalid}")

    provenance_series = df[LABEL_PROVENANCE_COLUMN].astype(str).str.upper()
    before = len(df)
    df = df[provenance_series.isin(allowed_set)].copy()
    after = len(df)

    if after == 0:
        raise ValueError(f"No rows match allowed provenance {sorted(allowed_set)}")

    if after < before:
        print(f"[INFO] Filtered {before - after} row(s) by label provenance")

    provenance_counts = df[LABEL_PROVENANCE_COLUMN].astype(str).str.upper().value_counts().to_dict()
    if provenance_counts == {"BRONZE": len(df)}:
        print("[WARN] Dataset contains only BRONZE labels; use SILVER/GOLD for final training.")

    return df, provenance_counts


def _resolve_allowed_provenance(
    df: pd.DataFrame,
    allowed_provenance: Optional[List[str]],
) -> Optional[List[str]]:
    """Apply default provenance policy when not explicitly provided."""
    if allowed_provenance:
        return allowed_provenance
    if LABEL_PROVENANCE_COLUMN not in df.columns:
        return None
    return DEFAULT_ALLOWED_PROVENANCE.copy()


def _extract_as_of_date_range(df: pd.DataFrame) -> Optional[Dict[str, str]]:
    """Return min/max as_of_date range when available."""
    if AS_OF_DATE_COLUMN not in df.columns:
        return None

    as_of_series = pd.to_datetime(df[AS_OF_DATE_COLUMN], errors="coerce")
    if as_of_series.notna().any():
        return {
            "min": as_of_series.min().date().isoformat(),
            "max": as_of_series.max().date().isoformat(),
        }
    return None


def _time_based_split(
    df: pd.DataFrame,
    feature_cols: List[str],
    target_col: str,
    test_size: float,
) -> Tuple[
    Optional[pd.DataFrame],
    Optional[pd.DataFrame],
    Optional[pd.Series],
    Optional[pd.Series],
    bool,
    Optional[Dict[str, str]],
]:
    """Perform a time-based split using as_of_date; returns split data and holdout window."""
    if AS_OF_DATE_COLUMN not in df.columns:
        return None, None, None, None, False, None

    as_of_series = pd.to_datetime(df[AS_OF_DATE_COLUMN], errors="coerce")
    if as_of_series.notna().sum() < 2 or as_of_series.nunique() <= 1:
        return None, None, None, None, False, None

    df_sorted = df.copy()
    df_sorted["_as_of_date"] = as_of_series
    df_sorted = df_sorted.sort_values("_as_of_date")
    split_index = int(len(df_sorted) * (1 - test_size))
    if split_index <= 0 or split_index >= len(df_sorted):
        return None, None, None, None, False, None

    X_sorted = df_sorted[feature_cols].copy()
    y_sorted = df_sorted[target_col].copy()
    holdout_window = {
        "train_end": df_sorted["_as_of_date"].iloc[split_index - 1].date().isoformat(),
        "test_start": df_sorted["_as_of_date"].iloc[split_index].date().isoformat(),
        "test_end": df_sorted["_as_of_date"].iloc[-1].date().isoformat(),
    }
    return (
        X_sorted.iloc[:split_index],
        X_sorted.iloc[split_index:],
        y_sorted.iloc[:split_index],
        y_sorted.iloc[split_index:],
        True,
        holdout_window,
    )


def build_pipeline(
    categorical_features,
    numeric_features,
    n_estimators: int = 200,
    random_state: int = 42,
) -> Pipeline:
    """Build a complete ML pipeline.

    - ColumnTransformer (OneHot + StandardScaler)
    - RandomForestClassifier
    """
    categorical_transformer = OneHotEncoder(handle_unknown="ignore")

    # Impute missing numeric values with mean, then scale
    numeric_transformer = Pipeline(
        [
            ("imputer", SimpleImputer(strategy="mean")),
            ("scaler", StandardScaler()),
        ]
    )

    preprocessor = ColumnTransformer(
        transformers=[
            ("cat", categorical_transformer, categorical_features),
            ("num", numeric_transformer, numeric_features),
        ]
    )

    clf = RandomForestClassifier(
        n_estimators=n_estimators,
        random_state=random_state,
        class_weight="balanced",
        n_jobs=-1,
    )

    pipeline = Pipeline(
        steps=[
            ("preprocess", preprocessor),
            ("clf", clf),
        ],
        memory=str(JOBLIB_CACHE_DIR),  # Cache transformers for better performance  # noqa: S106 - Not a password
    )

    return pipeline


def _prepare_features(df: pd.DataFrame, feature_cols: list, target_col: str) -> tuple:
    """Prepare features and target, handling missing columns."""
    available_features = [c for c in feature_cols if c in df.columns]
    missing_cols = [c for c in feature_cols if c not in df.columns]

    if missing_cols:
        print(f"[WARN] Colonnes manquantes (ignorées) : {missing_cols}")

    if not available_features:
        raise ValueError("Aucune feature disponible dans le dataset!")

    X = df[available_features].copy()
    y = df[target_col].copy()

    return X, y, available_features, missing_cols


def _identify_feature_types(df: pd.DataFrame, available_features: list) -> tuple:
    """Identify categorical and numeric features dynamically."""
    categorical_features = []
    numeric_features = []

    for col in available_features:
        if df[col].dtype == "object" or df[col].dtype.name == "category":
            categorical_features.append(col)
        else:
            numeric_features.append(col)

    return categorical_features, numeric_features


def _check_class_imbalance(y: pd.Series) -> tuple:
    """Check for class imbalance and print warnings. Returns (imbalance_ratio, class_counts)."""
    class_counts = y.value_counts()
    imbalance_ratio = class_counts.max() / class_counts.min()
    print(f"[INFO] Ratio de déséquilibre : {imbalance_ratio:.2f}")
    if imbalance_ratio > 3:
        print("[WARN] Déséquilibre des classes détecté. Utilisation de class_weight='balanced'")
    return imbalance_ratio, class_counts


def _compute_per_class_metrics(y_true: pd.Series, y_pred: np.ndarray) -> dict:
    """Calculate per-class precision/recall/F1 and accuracy."""
    labels = ["LOW", "MEDIUM", "HIGH"]
    cm = confusion_matrix(y_true, y_pred, labels=labels)
    precision, recall, f1, support = precision_recall_fscore_support(
        y_true,
        y_pred,
        labels=labels,
        average=None,
        zero_division=0,
    )

    per_class_metrics = {}
    print("\nMétriques par classe :")
    for i, level in enumerate(labels):
        support_count = int(support[i])
        accuracy = float(cm[i, i] / support_count) if support_count > 0 else 0.0
        per_class_metrics[level] = {
            "precision": round(float(precision[i]), 4),
            "recall": round(float(recall[i]), 4),
            "f1": round(float(f1[i]), 4),
            "accuracy": round(accuracy, 4),
            "support": support_count,
        }
        if support_count > 0:
            print(
                f"  {level}: precision={precision[i]:.2f} recall={recall[i]:.2f} "
                f"f1={f1[i]:.2f} support={support_count}"
            )
        else:
            print(f"  {level}: N/A (no samples)")
    return per_class_metrics


def _run_walk_forward_evaluation(
    df: pd.DataFrame,
    target_col: str,
    available_features: list,
    categorical_features: list,
    numeric_features: list,
    n_estimators: int,
    random_state: int,
    min_train_dates: int = 3,
    max_folds: int = 5,
):
    """Run walk-forward evaluation when enough temporal history exists."""
    if AS_OF_DATE_COLUMN not in df.columns:
        return None

    as_of_series = pd.to_datetime(df[AS_OF_DATE_COLUMN], errors="coerce")
    if as_of_series.notna().sum() < 2:
        return None

    df_sorted = df.copy()
    df_sorted["_as_of_date"] = as_of_series
    df_sorted = df_sorted.dropna(subset=["_as_of_date"]).sort_values("_as_of_date")
    unique_dates = sorted(df_sorted["_as_of_date"].unique())

    if len(unique_dates) < min_train_dates + 1:
        return None

    fold_indices = list(range(min_train_dates - 1, len(unique_dates) - 1))
    if len(fold_indices) > max_folds:
        fold_indices = fold_indices[-max_folds:]

    folds = []
    metrics_accumulator = {
        "accuracy": [],
        "precision": [],
        "recall": [],
        "f1_score": [],
        "macro_f1": [],
        "balanced_accuracy": [],
        "kappa": [],
        "weighted_kappa": [],
        "brier_score": [],
    }

    for idx in fold_indices:
        train_end = unique_dates[idx]
        test_date = unique_dates[idx + 1]

        train_df = df_sorted[df_sorted["_as_of_date"] <= train_end]
        test_df = df_sorted[df_sorted["_as_of_date"] == test_date]
        if train_df.empty or test_df.empty:
            continue

        x_train = train_df[available_features].copy()
        y_train = train_df[target_col].copy()
        x_test = test_df[available_features].copy()
        y_test = test_df[target_col].copy()

        pipeline = build_pipeline(
            categorical_features=categorical_features,
            numeric_features=numeric_features,
            n_estimators=n_estimators,
            random_state=random_state,
        )
        pipeline.fit(x_train, y_train)

        y_pred = pipeline.predict(x_test)
        accuracy = accuracy_score(y_test, y_pred)
        precision, recall, f1, _ = precision_recall_fscore_support(
            y_test,
            y_pred,
            labels=["LOW", "MEDIUM", "HIGH"],
            average="weighted",
            zero_division=0,
        )
        _macro_precision, _macro_recall, macro_f1, _ = precision_recall_fscore_support(
            y_test,
            y_pred,
            labels=["LOW", "MEDIUM", "HIGH"],
            average="macro",
            zero_division=0,
        )
        balanced_accuracy = balanced_accuracy_score(y_test, y_pred)
        kappa = 0.0
        weighted_kappa = 0.0
        if pd.Series(y_test).nunique() > 1 and pd.Series(y_pred).nunique() > 1:
            kappa = cohen_kappa_score(y_test, y_pred)
            weighted_kappa = cohen_kappa_score(y_test, y_pred, weights="quadratic")

        brier_score = None
        if hasattr(pipeline, "predict_proba"):
            try:
                y_proba = pipeline.predict_proba(x_test)
                class_labels = list(getattr(pipeline, "classes_", ["LOW", "MEDIUM", "HIGH"]))
                brier_values = []
                for label_index, label in enumerate(class_labels):
                    y_true_binary = (y_test == label).astype(int)
                    brier_values.append(brier_score_loss(y_true_binary, y_proba[:, label_index]))
                if brier_values:
                    brier_score = float(sum(brier_values) / len(brier_values))
            except Exception:  # noqa: BLE001
                brier_score = None

        fold_metrics = {
            "accuracy": float(accuracy),
            "precision": float(precision),
            "recall": float(recall),
            "f1_score": float(f1),
            "macro_f1": float(macro_f1),
            "balanced_accuracy": float(balanced_accuracy),
            "kappa": float(kappa),
            "weighted_kappa": float(weighted_kappa),
            "brier_score": brier_score,
        }
        folds.append(
            {
                "train_end": pd.Timestamp(train_end).date().isoformat(),
                "test_date": pd.Timestamp(test_date).date().isoformat(),
                "train_samples": len(x_train),
                "test_samples": len(x_test),
                "metrics": fold_metrics,
            }
        )

        for key, value in fold_metrics.items():
            if value is None:
                continue
            metrics_accumulator[key].append(float(value))

    if not folds:
        return None

    mean_metrics = {}
    for key, values in metrics_accumulator.items():
        if values:
            mean_metrics[key] = round(sum(values) / len(values), 4)

    return {
        "strategy": "expanding_window",
        "min_train_dates": min_train_dates,
        "max_folds": max_folds,
        "fold_count": len(folds),
        "mean_metrics": mean_metrics,
        "folds": folds,
    }


def train_model(
    csv_path: Path,
    output_model_path: Path,
    model_version: str = "v1",
    test_size: float = 0.2,
    random_state: int = 42,
    n_estimators: int = 200,
    allowed_provenance: Optional[List[str]] = None,
    use_time_split: bool = True,
):
    """Train the Future Skills ML model and save with metadata.

    Args:
        csv_path: Path to the input dataset CSV
        output_model_path: Path where the model will be saved
        model_version: Version identifier (e.g., 'v1', 'v2', 'v2.1')
        test_size: Proportion of test set
        random_state: Random seed for reproducibility
        n_estimators: Number of trees in RandomForest
    """
    training_start_time = datetime.now()

    print(f"[INFO] Chargement du dataset : {csv_path}")
    df = load_dataset(csv_path)
    # Use the detected target column
    target_col = getattr(df, "_target_col", "future_need_level")

    allowed_provenance = _resolve_allowed_provenance(df, allowed_provenance)
    if allowed_provenance:
        print(f"[INFO] Provenance autorisée: {allowed_provenance}")
    df, provenance_counts = _apply_label_provenance_filter(df, allowed_provenance)
    as_of_date_range = _extract_as_of_date_range(df)

    # Définir les features et la cible (UPDATED with new features)
    feature_cols = [
        "job_role_name",
        "skill_name",
        "skill_category",
        "job_department",
        "trend_score",
        "internal_usage",
        "training_requests",
        "scarcity_index",
        "hiring_difficulty",
        "avg_salary_k",
        "economic_indicator",
        "trend_momentum",
        "trend_acceleration",
        "trend_volatility",
        "trend_persistence",
        "internal_usage_momentum",
        "training_requests_momentum",
        "internal_usage_lag_1",
        "internal_usage_lag_2",
        "internal_usage_roll_mean_3",
        "training_requests_lag_1",
        "training_requests_lag_2",
        "training_requests_roll_mean_3",
        "economic_indicator_lag_1",
        "economic_indicator_lag_2",
        "economic_indicator_roll_mean_3",
        "trend_stability_flag",
        "internal_usage_stability_flag",
        "training_requests_stability_flag",
        "data_quality_window_coverage",
        "data_quality_missing_flag",
        "data_quality_stale_flag",
        "data_quality_low_sample_flag",
        "is_it_department",
        "is_senior_role",
        "is_technical_skill",
        "dept_skill_alignment",
        "forecast_trend_score",
        "forecast_internal_usage",
        "forecast_training_requests",
        "forecast_need_score",
    ]

    # Prepare features and target
    X, y, available_features, missing_cols = _prepare_features(df, feature_cols, target_col)

    # Identify feature types
    categorical_features, numeric_features = _identify_feature_types(df, available_features)

    print(f"[INFO] Features catégorielles : {categorical_features}")
    print(f"[INFO] Features numériques : {numeric_features}")
    print(f"[INFO] Nombre total d'exemples : {len(df)}")
    print("[INFO] Répartition des classes :")
    print(y.value_counts())

    # Check for class imbalance
    imbalance_ratio, class_counts = _check_class_imbalance(y)

    X_train = X_test = y_train = y_test = None
    time_split_used = False
    holdout_window = None
    if use_time_split:
        X_train, X_test, y_train, y_test, time_split_used, holdout_window = _time_based_split(
            df,
            available_features,
            target_col,
            test_size,
        )

    if not time_split_used:
        X_train, X_test, y_train, y_test = train_test_split(
            X,
            y,
            test_size=test_size,
            random_state=random_state,
            stratify=y,
        )

    if time_split_used:
        print("[INFO] Split temporel actif (as_of_date).")
    print(f"[INFO] Taille train : {len(X_train)}, test : {len(X_test)}")

    # Build and train pipeline
    pipeline = build_pipeline(
        categorical_features=categorical_features,
        numeric_features=numeric_features,
        n_estimators=n_estimators,
        random_state=random_state,
    )

    print(f"[INFO] Entraînement du modèle RandomForestClassifier (n_estimators={n_estimators})...")
    pipeline.fit(X_train, y_train)

    training_end_time = datetime.now()
    training_duration = (training_end_time - training_start_time).total_seconds()

    # Evaluation
    print("[INFO] Évaluation sur le set de test :")
    y_pred = pipeline.predict(X_test)

    # Compute metrics
    accuracy = accuracy_score(y_test, y_pred)
    precision, recall, f1, _ = precision_recall_fscore_support(
        y_test, y_pred, labels=["LOW", "MEDIUM", "HIGH"], average="weighted"
    )
    macro_precision, macro_recall, macro_f1, _ = precision_recall_fscore_support(
        y_test, y_pred, labels=["LOW", "MEDIUM", "HIGH"], average="macro", zero_division=0
    )
    balanced_accuracy = balanced_accuracy_score(y_test, y_pred)
    kappa = cohen_kappa_score(y_test, y_pred)
    weighted_kappa = cohen_kappa_score(y_test, y_pred, weights="quadratic")

    brier_score = None
    if hasattr(pipeline, "predict_proba"):
        try:
            y_proba = pipeline.predict_proba(X_test)
            class_labels = list(getattr(pipeline, "classes_", ["LOW", "MEDIUM", "HIGH"]))
            brier_values = []
            for idx, label in enumerate(class_labels):
                y_true_binary = (y_test == label).astype(int)
                brier_values.append(brier_score_loss(y_true_binary, y_proba[:, idx]))
            if brier_values:
                brier_score = float(sum(brier_values) / len(brier_values))
        except Exception as exc:  # noqa: BLE001
            print(f"[WARN] Brier score computation failed: {exc}")

    print("\nClassification report :")
    print(classification_report(y_test, y_pred, digits=4))
    print(f"\nMacro F1: {macro_f1:.4f}")
    print(f"Balanced accuracy: {balanced_accuracy:.4f}")

    print("\nMatrice de confusion :")
    cm = confusion_matrix(y_test, y_pred, labels=["LOW", "MEDIUM", "HIGH"])
    print(cm)

    # Calculate per-class metrics using helper function
    per_class_metrics = _compute_per_class_metrics(y_test, y_pred)

    # Feature importance
    clf = pipeline.named_steps["clf"]  # noqa: PD011 - sklearn pipeline access pattern
    print(f"[INFO] Classes apprises par le modèle : {clf.classes_}")

    feature_importance_dict = {}
    if hasattr(clf, "feature_importances_"):
        print("\n[INFO] Importance des features :")
        preprocessor = pipeline.named_steps["preprocess"]  # noqa: PD011 - sklearn pipeline access pattern

        # Get feature names after preprocessing
        cat_features = []
        if categorical_features:
            cat_transformer = preprocessor.named_transformers_["cat"]  # noqa: PD011 - sklearn pipeline access pattern
            if hasattr(cat_transformer, "get_feature_names_out"):
                cat_features = cat_transformer.get_feature_names_out(categorical_features).tolist()

        all_features = cat_features + numeric_features

        if len(all_features) == len(clf.feature_importances_):
            feature_importance = sorted(
                zip(all_features, clf.feature_importances_),
                key=lambda x: x[1],
                reverse=True,
            )
            for feat, importance in feature_importance[:10]:  # Top 10
                print(f"  {feat}: {importance:.4f}")
                feature_importance_dict[feat] = float(importance)

    # Sauvegarde du pipeline complet
    output_model_path.parent.mkdir(parents=True, exist_ok=True)
    joblib.dump(pipeline, output_model_path)
    print(f"\n[SUCCESS] Modèle sauvegardé dans : {output_model_path}")

    # Generate and save metadata
    walk_forward = None
    if use_time_split:
        walk_forward = _run_walk_forward_evaluation(
            df=df,
            target_col=target_col,
            available_features=available_features,
            categorical_features=categorical_features,
            numeric_features=numeric_features,
            n_estimators=n_estimators,
            random_state=random_state,
        )

    metadata = {
        "model_version": model_version,
        "training_date": training_start_time.isoformat(),
        "training_duration_seconds": round(training_duration, 2),
        "dataset": {
            "csv_path": str(csv_path),
            "total_samples": len(df),
            "train_samples": len(X_train),
            "test_samples": len(X_test),
            "features_used": available_features,
            "features_missing": missing_cols,
            "categorical_features": categorical_features,
            "numeric_features": numeric_features,
            "class_distribution": {k: int(v) for k, v in class_counts.items()},
            "imbalance_ratio": round(float(imbalance_ratio), 2),
            "label_provenance_counts": provenance_counts,
            "as_of_date_range": as_of_date_range,
            "time_split_used": time_split_used,
            "holdout_window": holdout_window,
        },
        "hyperparameters": {
            "n_estimators": n_estimators,
            "random_state": random_state,
            "test_size": test_size,
            "class_weight": "balanced",
        },
        "metrics": {
            "accuracy": round(float(accuracy), 4),
            "precision_weighted": round(float(precision), 4),
            "recall_weighted": round(float(recall), 4),
            "f1_weighted": round(float(f1), 4),
            "macro_precision": round(float(macro_precision), 4),
            "macro_recall": round(float(macro_recall), 4),
            "macro_f1": round(float(macro_f1), 4),
            "balanced_accuracy": round(float(balanced_accuracy), 4),
            "kappa": round(float(kappa), 4),
            "weighted_kappa": round(float(weighted_kappa), 4),
            "brier_score": round(float(brier_score), 4) if brier_score is not None else None,
            "per_class": per_class_metrics,
            "confusion_matrix": cm.tolist(),
            "walk_forward": walk_forward,
        },
        "feature_importance_top10": dict(list(feature_importance_dict.items())[:10]),
        "model_classes": clf.classes_.tolist(),
    }

    # Save metadata JSON
    metadata_path = output_model_path.with_suffix(".json")
    with open(metadata_path, "w", encoding="utf-8") as f:
        json.dump(metadata, f, indent=2, ensure_ascii=False)

    print(f"[SUCCESS] Métadonnées sauvegardées dans : {metadata_path}")
    print(f"[SUCCESS] Le modèle utilise {len(available_features)} features")

    return metadata


def main():
    """Main entry point for training the Future Skills ML model.

    Parses command line arguments and orchestrates the model training process.
    Supports configuration of dataset path, output location, model version,
    and training hyperparameters.
    """
    default_csv = DEFAULT_DATASET_DIR / "future_skills_dataset.csv"
    default_model = DEFAULT_MODEL_DIR / "future_skills_model.pkl"

    parser = argparse.ArgumentParser(description="Entraîne le modèle ML pour le Module 3 - Future Skills.")
    parser.add_argument(
        "--csv",
        type=str,
        default=str(default_csv),
        help=f"Chemin vers le dataset CSV (par défaut: {default_csv})",
    )
    parser.add_argument(
        "--output",
        type=str,
        default=str(default_model),
        help=f"Chemin de sortie du modèle .pkl (par défaut: {default_model})",
    )
    parser.add_argument(
        "--version",
        type=str,
        default="v1",
        help="Version du modèle (ex: v1, v2, v2.1). Utilisé pour la traçabilité.",
    )
    parser.add_argument(
        "--test-size",
        type=float,
        default=0.2,
        help="Proportion du set de test (par défaut: 0.2).",
    )
    parser.add_argument(
        "--random-state",
        type=int,
        default=42,
        help="Seed aléatoire (par défaut: 42).",
    )
    parser.add_argument(
        "--n-estimators",
        type=int,
        default=200,
        help="Nombre d'arbres dans RandomForest (par défaut: 200).",
    )
    parser.add_argument(
        "--allowed-provenance",
        type=str,
        default="SILVER,GOLD",
        help="Liste des provenances autorisees (par defaut: SILVER,GOLD).",
    )
    parser.add_argument(
        "--use-time-split",
        dest="use_time_split",
        action="store_true",
        help="Utiliser un split temporel si as_of_date est disponible.",
    )
    parser.add_argument(
        "--no-time-split",
        dest="use_time_split",
        action="store_false",
        help="Desactiver le split temporel.",
    )
    parser.set_defaults(use_time_split=True)

    args = parser.parse_args()

    csv_path = Path(args.csv)
    output_model_path = Path(args.output)

    # If version is provided and output doesn't include version, add it
    if args.version and args.version not in output_model_path.stem:
        output_model_path = output_model_path.parent / f"{output_model_path.stem}_{args.version}.pkl"
        print(f"[INFO] Nom du modèle ajusté avec version : {output_model_path}")

    allowed_provenance = None
    if args.allowed_provenance:
        allowed_provenance = [value.strip().upper() for value in args.allowed_provenance.split(",") if value.strip()]

    metadata = train_model(
        csv_path=csv_path,
        output_model_path=output_model_path,
        model_version=args.version,
        test_size=args.test_size,
        random_state=args.random_state,
        n_estimators=args.n_estimators,
        allowed_provenance=allowed_provenance,
        use_time_split=args.use_time_split,
    )

    print("\n" + "=" * 60)
    print("📊 RÉSUMÉ DE L'ENTRAÎNEMENT")
    print("=" * 60)
    print(f"Version: {metadata['model_version']}")
    print(f"Date: {metadata['training_date']}")
    print(f"Durée: {metadata['training_duration_seconds']}s")
    print(f"Précision: {metadata['metrics']['accuracy']:.2%}")
    print(f"F1-score: {metadata['metrics']['f1_weighted']:.4f}")
    print("=" * 60)


if __name__ == "__main__":
    main()
