ROLE_TO_BASE_GROUP = {
    "HR": "HR",
    "MANAGER": "MANAGER",
    "EMPLOYEE": "EMPLOYEE",
}

BASE_ROLE_GROUPS = set(ROLE_TO_BASE_GROUP.values())

LEGACY_HR_GROUPS = {"DRH", "RESPONSABLE_RH"}

HR_GROUPS = {"HR", "HR_ADMIN"} | LEGACY_HR_GROUPS
MANAGER_GROUPS = {"MANAGER", "MANAGER_ADMIN"}
EMPLOYEE_GROUPS = {"EMPLOYEE", "EMPLOYEE_ADMIN"}

AUDITOR_GROUPS = {"AUDITOR"}
SECURITY_ADMIN_GROUPS = {"SECURITY_ADMIN"}
SUPPORT_GROUPS = {"SUPPORT"}

DEFAULT_GROUPS = sorted(
    HR_GROUPS
    | MANAGER_GROUPS
    | EMPLOYEE_GROUPS
    | AUDITOR_GROUPS
    | SECURITY_ADMIN_GROUPS
    | SUPPORT_GROUPS
    | LEGACY_HR_GROUPS
)
