# Generated by Django 5.2.16 on 2026-07-19 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_external_auth_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
    ]
