# Generated by Django 5.2.15 on 2026-07-04 01:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeadLetterTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('task_name', models.CharField(db_index=True, max_length=255)),
                ('args', models.JSONField(default=list, help_text='Positional arguments')),
                ('kwargs', models.JSONField(default=dict, help_text='Keyword arguments')),
                ('exception_type', models.CharField(max_length=255)),
                ('exception_message', models.TextField()),
                ('exception_traceback', models.TextField(blank=True)),
                ('retries', models.IntegerField(default=0)),
                ('failed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reprocessed', models.BooleanField(db_index=True, default=False)),
                ('reprocessed_at', models.DateTimeField(blank=True, null=True)),
                ('reprocessing_result', models.TextField(blank=True)),
                ('worker_name', models.CharField(blank=True, max_length=255)),
                ('queue_name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'celery_dead_letter_queue',
                'ordering': ['-failed_at'],
                'indexes': [models.Index(fields=['task_name', 'failed_at'], name='celery_dead_task_na_31b9f2_idx'), models.Index(fields=['reprocessed', 'failed_at'], name='celery_dead_reproce_d2ce63_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('task_name', models.CharField(db_index=True, max_length=255)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('queue_time', models.FloatField(blank=True, help_text='Time spent in queue', null=True)),
                ('execution_time', models.FloatField(blank=True, help_text='Actual execution time', null=True)),
                ('total_time', models.FloatField(blank=True, help_text='Total time from receive to complete', null=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('RETRY', 'Retry'), ('REVOKED', 'Revoked')], db_index=True, default='RECEIVED', max_length=20)),
                ('result', models.JSONField(blank=True, null=True)),
                ('exception_type', models.CharField(blank=True, max_length=255)),
                ('exception_message', models.TextField(blank=True)),
                ('traceback', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(blank=True, null=True)),
                ('worker_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('queue_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('memory_usage_mb', models.FloatField(blank=True, null=True)),
                ('cpu_percent', models.FloatField(blank=True, null=True)),
                ('args', models.JSONField(default=list)),
                ('kwargs', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'celery_task_execution',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['task_name', 'status', 'started_at'], name='celery_task_task_na_224b0f_idx'), models.Index(fields=['worker_name', 'started_at'], name='celery_task_worker__b64d8f_idx'), models.Index(fields=['queue_name', 'started_at'], name='celery_task_queue_n_0d54fb_idx'), models.Index(fields=['status', 'started_at'], name='celery_task_status_b3f8ec_idx')],
            },
        ),
    ]
