# Generated by Django 5.2.8 on 2025-11-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("future_skills", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EconomicReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "source_name",
                    models.CharField(
                        help_text="Source du rapport (ex : Banque Mondiale, FMI, HCP, WEF...).",
                        max_length=200,
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "indicator",
                    models.CharField(
                        help_text="Nom de l’indicateur (ex : 'Taux chômage IT', 'Investissement IA').",
                        max_length=150,
                    ),
                ),
                (
                    "value",
                    models.FloatField(
                        help_text="Valeur de l’indicateur (pourcentage, indice, budget…)."
                    ),
                ),
                (
                    "sector",
                    models.CharField(
                        blank=True,
                        help_text="Secteur concerné (ex : Tech, Industrie, RH...).",
                        max_length=150,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Rapport économique",
                "verbose_name_plural": "Rapports économiques",
                "ordering": ["-year", "title"],
            },
        ),
    ]
