# Generated by Django 5.2.8 on 2025-11-26 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_skills', '0002_economicreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRInvestmentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizon_years', models.PositiveIntegerField(help_text='Horizon temporel de la recommandation (en années).')),
                ('priority_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], help_text='Priorité de la recommandation (LOW / MEDIUM / HIGH).', max_length=10)),
                ('recommended_action', models.CharField(choices=[('TRAINING', 'Investir en formation'), ('HIRING', 'Recruter de nouveaux talents'), ('RESKILL', 'Reskilling interne')], help_text='Action RH recommandée (formation, recrutement, reskilling).', max_length=20)),
                ('budget_hint', models.FloatField(blank=True, help_text='Indice ou estimation de budget (optionnel, en K€ ou KMAD selon contexte).', null=True)),
                ('rationale', models.TextField(blank=True, help_text='Explication textuelle de la recommandation pour le décideur RH.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_role', models.ForeignKey(blank=True, help_text='Rôle cible de la recommandation (optionnel si globale à la compétence).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_recommendations', to='future_skills.jobrole')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_recommendations', to='future_skills.skill')),
            ],
            options={
                'verbose_name': 'Recommandation RH',
                'verbose_name_plural': 'Recommandations RH',
                'ordering': ['-created_at'],
                'unique_together': {('job_role', 'skill', 'horizon_years')},
            },
        ),
    ]
