# Generated by Django 5.2.8 on 2025-11-27 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("future_skills", "0006_employee"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_date", models.DateTimeField(auto_now_add=True)),
                (
                    "model_version",
                    models.CharField(
                        help_text="Version identifier for the trained model (e.g., 'v1', 'v2.1').",
                        max_length=50,
                    ),
                ),
                (
                    "model_path",
                    models.CharField(
                        help_text="File system path where the model was saved.",
                        max_length=500,
                    ),
                ),
                (
                    "dataset_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to the training dataset CSV file.",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "test_split",
                    models.FloatField(
                        default=0.2,
                        help_text="Test set split ratio (e.g., 0.2 = 20% test).",
                    ),
                ),
                (
                    "n_estimators",
                    models.IntegerField(
                        default=200,
                        help_text="Number of trees in RandomForest classifier.",
                    ),
                ),
                (
                    "random_state",
                    models.IntegerField(
                        default=42, help_text="Random seed for reproducibility."
                    ),
                ),
                (
                    "accuracy",
                    models.FloatField(
                        help_text="Overall accuracy on test set (0.0 to 1.0)."
                    ),
                ),
                (
                    "precision",
                    models.FloatField(
                        help_text="Weighted average precision on test set."
                    ),
                ),
                (
                    "recall",
                    models.FloatField(help_text="Weighted average recall on test set."),
                ),
                (
                    "f1_score",
                    models.FloatField(
                        help_text="Weighted average F1-score on test set."
                    ),
                ),
                (
                    "total_samples",
                    models.IntegerField(
                        help_text="Total number of samples in the dataset."
                    ),
                ),
                (
                    "train_samples",
                    models.IntegerField(help_text="Number of samples in training set."),
                ),
                (
                    "test_samples",
                    models.IntegerField(help_text="Number of samples in test set."),
                ),
                (
                    "training_duration_seconds",
                    models.FloatField(help_text="Total training duration in seconds."),
                ),
                (
                    "per_class_metrics",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per-class accuracy and support counts (LOW, MEDIUM, HIGH).",
                    ),
                ),
                (
                    "features_used",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of features used for training.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes or comments about this training run.",
                        null=True,
                    ),
                ),
                (
                    "trained_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered the training (null if CLI).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="training_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Training Run",
                "verbose_name_plural": "Training Runs",
                "ordering": ["-run_date"],
                "indexes": [
                    models.Index(
                        fields=["-run_date"], name="future_skil_run_dat_205663_idx"
                    ),
                    models.Index(
                        fields=["model_version"], name="future_skil_model_v_7f9524_idx"
                    ),
                ],
            },
        ),
    ]
