# Generated by Django 5.2.8 on 2025-11-28 14:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("future_skills", "0009_employee_skills"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobrole",
            options={
                "ordering": ["name"],
                "verbose_name": "Rôle professionnel",
                "verbose_name_plural": "Rôles professionnels",
            },
        ),
        migrations.AlterModelOptions(
            name="skill",
            options={
                "ordering": ["name"],
                "verbose_name": "Compétence",
                "verbose_name_plural": "Compétences",
            },
        ),
        migrations.AddIndex(
            model_name="economicreport",
            index=models.Index(fields=["-year"], name="future_skil_year_796aea_idx"),
        ),
        migrations.AddIndex(
            model_name="economicreport",
            index=models.Index(fields=["sector"], name="future_skil_sector_e2bb79_idx"),
        ),
        migrations.AddIndex(
            model_name="economicreport",
            index=models.Index(
                fields=["indicator"], name="future_skil_indicat_0232ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="economicreport",
            index=models.Index(
                fields=["sector", "-year"], name="future_skil_sector_eb4733_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["email"], name="future_skil_email_323a2e_idx"),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["department"], name="future_skil_departm_b0704d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["job_role"], name="future_skil_job_rol_7cd04a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["name"], name="future_skil_name_c89200_idx"),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["job_role", "department"], name="future_skil_job_rol_2c8f4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="futureskillprediction",
            index=models.Index(
                fields=["job_role"], name="future_skil_job_rol_b2822c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="futureskillprediction",
            index=models.Index(fields=["skill"], name="future_skil_skill_i_40f5e0_idx"),
        ),
        migrations.AddIndex(
            model_name="futureskillprediction",
            index=models.Index(
                fields=["horizon_years"], name="future_skil_horizon_10f7da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="futureskillprediction",
            index=models.Index(fields=["level"], name="future_skil_level_e35773_idx"),
        ),
        migrations.AddIndex(
            model_name="futureskillprediction",
            index=models.Index(fields=["-score"], name="future_skil_score_6a9d80_idx"),
        ),
        migrations.AddIndex(
            model_name="futureskillprediction",
            index=models.Index(
                fields=["-created_at"], name="future_skil_created_73130b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="futureskillprediction",
            index=models.Index(
                fields=["job_role", "horizon_years"],
                name="future_skil_job_rol_31504e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="futureskillprediction",
            index=models.Index(
                fields=["skill", "level"], name="future_skil_skill_i_9a5ffd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="futureskillprediction",
            index=models.Index(
                fields=["horizon_years", "-score"],
                name="future_skil_horizon_ef0b13_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="hrinvestmentrecommendation",
            index=models.Index(fields=["skill"], name="future_skil_skill_i_6c0fbd_idx"),
        ),
        migrations.AddIndex(
            model_name="hrinvestmentrecommendation",
            index=models.Index(
                fields=["job_role"], name="future_skil_job_rol_9c1b2c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hrinvestmentrecommendation",
            index=models.Index(
                fields=["horizon_years"], name="future_skil_horizon_810407_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hrinvestmentrecommendation",
            index=models.Index(
                fields=["priority_level"], name="future_skil_priorit_3cda16_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hrinvestmentrecommendation",
            index=models.Index(
                fields=["recommended_action"], name="future_skil_recomme_45d56f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hrinvestmentrecommendation",
            index=models.Index(
                fields=["-created_at"], name="future_skil_created_e22b49_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hrinvestmentrecommendation",
            index=models.Index(
                fields=["skill", "priority_level"],
                name="future_skil_skill_i_06d618_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="hrinvestmentrecommendation",
            index=models.Index(
                fields=["job_role", "horizon_years"],
                name="future_skil_job_rol_bb8bb1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="hrinvestmentrecommendation",
            index=models.Index(
                fields=["priority_level", "recommended_action"],
                name="future_skil_priorit_06b919_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="jobrole",
            index=models.Index(fields=["name"], name="future_skil_name_af27c6_idx"),
        ),
        migrations.AddIndex(
            model_name="jobrole",
            index=models.Index(
                fields=["department"], name="future_skil_departm_2895f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="markettrend",
            index=models.Index(fields=["-year"], name="future_skil_year_387204_idx"),
        ),
        migrations.AddIndex(
            model_name="markettrend",
            index=models.Index(fields=["sector"], name="future_skil_sector_693918_idx"),
        ),
        migrations.AddIndex(
            model_name="markettrend",
            index=models.Index(
                fields=["-trend_score"], name="future_skil_trend_s_efc554_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="markettrend",
            index=models.Index(
                fields=["sector", "-year"], name="future_skil_sector_aaac35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="predictionrun",
            index=models.Index(
                fields=["-run_date"], name="future_skil_run_dat_a36d0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="predictionrun",
            index=models.Index(
                fields=["run_by"], name="future_skil_run_by__bb7da6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(fields=["name"], name="future_skil_name_a4b097_idx"),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(
                fields=["category"], name="future_skil_categor_f3214f_idx"
            ),
        ),
    ]
