# Generated by Django 5.2.8 on 2026-01-09 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_skills', '0011_future_skill_prediction_metadata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingrun',
            options={'ordering': ['-run_date'], 'verbose_name': 'Entraînement ML', 'verbose_name_plural': 'Entraînements ML'},
        ),
        migrations.CreateModel(
            name='FutureSkillSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of_date', models.DateField(help_text='Snapshot date for the captured signals.')),
                ('trend_score', models.FloatField(help_text='Trend score at snapshot time (0-1).')),
                ('internal_usage', models.FloatField(help_text='Estimated internal usage at snapshot time (0-1).')),
                ('training_requests', models.FloatField(help_text='Estimated training requests at snapshot time.')),
                ('scarcity_index', models.FloatField(help_text='Estimated scarcity index at snapshot time (0-1).')),
                ('hiring_difficulty', models.FloatField(help_text='Estimated hiring difficulty at snapshot time (0-1).')),
                ('avg_salary_k', models.FloatField(help_text='Estimated average salary at snapshot time (K/year).')),
                ('economic_indicator', models.FloatField(help_text='Economic indicator at snapshot time (0-1).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_snapshots', to='future_skills.jobrole')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_snapshots', to='future_skills.skill')),
            ],
            options={
                'verbose_name': 'Skill snapshot',
                'verbose_name_plural': 'Skill snapshots',
                'indexes': [models.Index(fields=['as_of_date'], name='future_skil_as_of_d_496266_idx'), models.Index(fields=['job_role'], name='future_skil_job_rol_84ece8_idx'), models.Index(fields=['skill'], name='future_skil_skill_i_4156f1_idx'), models.Index(fields=['job_role', 'skill', 'as_of_date'], name='future_skil_job_rol_65b341_idx')],
                'unique_together': {('job_role', 'skill', 'as_of_date')},
            },
        ),
    ]
