# Generated by Django 5.2.8 on 2026-01-10 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_skills', '0013_future_skill_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Domaine',
                'verbose_name_plural': 'Domaines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fonction',
                'verbose_name_plural': 'Fonctions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Industrie',
                'verbose_name_plural': 'Industries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SkillDomainMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0, help_text='Mapping weight between 0 and 1.')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mapping compétence/domaine',
                'verbose_name_plural': 'Mappings compétences/domaines',
            },
        ),
        migrations.RenameIndex(
            model_name='futureskilllabel',
            new_name='future_skil_as_of_d_ba2b08_idx',
            old_name='future_skil_as_of_d_11c2d0_idx',
        ),
        migrations.RenameIndex(
            model_name='futureskilllabel',
            new_name='future_skil_job_rol_f504bd_idx',
            old_name='future_skil_job_rol_9d37d6_idx',
        ),
        migrations.RenameIndex(
            model_name='futureskilllabel',
            new_name='future_skil_skill_i_92bb4c_idx',
            old_name='future_skil_skill_id_4f5e10_idx',
        ),
        migrations.RenameIndex(
            model_name='futureskilllabel',
            new_name='future_skil_horizon_600725_idx',
            old_name='future_skil_horizon_394f30_idx',
        ),
        migrations.RenameIndex(
            model_name='futureskilllabel',
            new_name='future_skil_job_rol_7e7392_idx',
            old_name='future_skil_job_rol_3d1ef7_idx',
        ),
        migrations.AddField(
            model_name='jobrole',
            name='domain',
            field=models.ForeignKey(blank=True, help_text='Domaine fonctionnel associé au rôle (optionnel).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_roles', to='future_skills.domain'),
        ),
        migrations.AddField(
            model_name='markettrend',
            name='domain',
            field=models.ForeignKey(blank=True, help_text='Domaine associé à la tendance (optionnel).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_trends', to='future_skills.domain'),
        ),
        migrations.AddIndex(
            model_name='function',
            index=models.Index(fields=['code'], name='future_skil_code_b6db25_idx'),
        ),
        migrations.AddIndex(
            model_name='function',
            index=models.Index(fields=['name'], name='future_skil_name_570dd5_idx'),
        ),
        migrations.AddField(
            model_name='domain',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domains', to='future_skills.function'),
        ),
        migrations.AddField(
            model_name='markettrend',
            name='function',
            field=models.ForeignKey(blank=True, help_text='Fonction associée à la tendance (optionnel).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_trends', to='future_skills.function'),
        ),
        migrations.AddIndex(
            model_name='industry',
            index=models.Index(fields=['code'], name='future_skil_code_75bae3_idx'),
        ),
        migrations.AddIndex(
            model_name='industry',
            index=models.Index(fields=['name'], name='future_skil_name_5062bf_idx'),
        ),
        migrations.AddField(
            model_name='economicreport',
            name='industry',
            field=models.ForeignKey(blank=True, help_text='Industrie associée au rapport (optionnel).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='economic_reports', to='future_skills.industry'),
        ),
        migrations.AddField(
            model_name='jobrole',
            name='industry',
            field=models.ForeignKey(blank=True, help_text='Industrie associée au rôle (optionnel).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_roles', to='future_skills.industry'),
        ),
        migrations.AddField(
            model_name='markettrend',
            name='industry',
            field=models.ForeignKey(blank=True, help_text='Industrie associée à la tendance (optionnel).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_trends', to='future_skills.industry'),
        ),
        migrations.AddIndex(
            model_name='economicreport',
            index=models.Index(fields=['industry'], name='future_skil_industr_d94aa3_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrole',
            index=models.Index(fields=['industry'], name='future_skil_industr_c70459_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrole',
            index=models.Index(fields=['domain'], name='future_skil_domain__6e3e71_idx'),
        ),
        migrations.AddIndex(
            model_name='markettrend',
            index=models.Index(fields=['industry'], name='future_skil_industr_db37b9_idx'),
        ),
        migrations.AddIndex(
            model_name='markettrend',
            index=models.Index(fields=['function'], name='future_skil_functio_5b630c_idx'),
        ),
        migrations.AddIndex(
            model_name='markettrend',
            index=models.Index(fields=['domain'], name='future_skil_domain__3d1d95_idx'),
        ),
        migrations.AddField(
            model_name='skilldomainmap',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_mappings', to='future_skills.domain'),
        ),
        migrations.AddField(
            model_name='skilldomainmap',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_mappings', to='future_skills.skill'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['code'], name='future_skil_code_7888cc_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['function'], name='future_skil_functio_72fd0c_idx'),
        ),
        migrations.AddIndex(
            model_name='skilldomainmap',
            index=models.Index(fields=['skill'], name='future_skil_skill_i_e36c93_idx'),
        ),
        migrations.AddIndex(
            model_name='skilldomainmap',
            index=models.Index(fields=['domain'], name='future_skil_domain__955bb9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='skilldomainmap',
            unique_together={('skill', 'domain')},
        ),
    ]
