# Generated by Django 5.2.8 on 2026-01-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_skills', '0014_domain_function_industry_skilldomainmap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='description_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='Multilingual domain descriptions.'),
        ),
        migrations.AddField(
            model_name='domain',
            name='name_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='Multilingual domain names.'),
        ),
        migrations.AddField(
            model_name='economicreport',
            name='indicator_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='Multilingual indicator names.'),
        ),
        migrations.AddField(
            model_name='economicreport',
            name='title_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='Multilingual report titles.'),
        ),
        migrations.AddField(
            model_name='function',
            name='description_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='Multilingual function descriptions.'),
        ),
        migrations.AddField(
            model_name='function',
            name='name_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='Multilingual function names.'),
        ),
        migrations.AddField(
            model_name='industry',
            name='description_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='Multilingual industry descriptions.'),
        ),
        migrations.AddField(
            model_name='industry',
            name='name_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='Multilingual industry names.'),
        ),
        migrations.AddField(
            model_name='jobrole',
            name='description_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='Multilingual role descriptions.'),
        ),
        migrations.AddField(
            model_name='jobrole',
            name='name_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='Multilingual role names.'),
        ),
        migrations.AddField(
            model_name='markettrend',
            name='description_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='Multilingual trend descriptions.'),
        ),
        migrations.AddField(
            model_name='markettrend',
            name='title_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='Multilingual trend titles.'),
        ),
        migrations.AddField(
            model_name='skill',
            name='description_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='Multilingual skill descriptions.'),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='Multilingual skill names.'),
        ),
    ]
