# Generated by Django 5.2.15 on 2026-07-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_skills', '0015_domain_description_i18n_domain_name_i18n_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='platform_code',
            field=models.SlugField(blank=True, help_text='Canonical SmartHR360 platform skill code (= core-hr Skill.code, ADR-007). Enables code-based matching across services.', null=True, unique=True),
        ),
    ]
